project:
  type: website
  output-dir: docs
  
website:
  title: "æ‰¿"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - projects.qmd
      - Final_check-in_2.qmd
    tools:
      - icon: linkedin
        href: https://www.linkedin.com/in/kuan-cheng-lee/
      - icon: github
        href: https://github.com/klee201/MyWebsite
  page-footer:
    right: "Built with [Quarto](https://quarto.org/)"
    left: "&copy; Copyright 2025, Kuan-Cheng Lee"

format:
  html:
    theme: cerulean
    toc: true

editor: source

