project:
  type: website
  output-dir: docs
  
website:
  title: "My Personal Website"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - projects.qmd
    tools:
      - icon: linkedin
        href: https://www.linkedin.com/in/kuan-cheng-lee/
      - icon: github
        href: https://github.com/klee201/MyWebsite
  page-footer:
    right: "Built with [Quarto](https://quarto.org/)"
    left: "&copy; Copyright 2023, YOUR NAME"

format:
  html:
    theme: cerulean
    toc: true

editor: source

